# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-28 09:58
from __future__ import unicode_literals

from django.db import migrations, models
import recommendersys.models
import recommendersys.validator


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_set', models.FileField(upload_to=recommendersys.models.reviews_directory_path, validators=[recommendersys.validator.validate_file_extension])),
                ('user_set', models.FileField(upload_to=recommendersys.models.reviews_directory_path, validators=[recommendersys.validator.validate_file_extension])),
                ('testing_set', models.FileField(upload_to=recommendersys.models.reviews_directory_path, validators=[recommendersys.validator.validate_file_extension])),
                ('note', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
